name: Main Pipeline

on:
  push:
    branches:
        - 'main'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  run-linters:
    # Job to Start the ES Linter and check the code to be deployed
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      # Check out Git repository
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install Node.js dependencies
      - name: Install Node.js dependencies
        run: npm ci

      # Run linters
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          commit_message: Fix styling

  pages-build-and-deploy:
    # Single deploy & build job 
    name: Pages build and deployment
    if: ${{ needs.run-linters.result == 'success' }}
    needs: run-linters # This ensures that this job only runs if the run-linters job was successful
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
