name: Stage Pipeline

on:
  # Defines this Pipeline only to Run on the 'stage' by a push and a push into it
  push:
    branches:
      - 'stage'
  pull_request:
    branches:
      - 'stage'

permissions:
  # Provides the needed permissions to the generated Token
  contents: write
  pages: write
  id-token: write

jobs:
  run-linters:
    # Job to start the ESLint and check the code to be deployed
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      # Check out Git repository
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install Node.js dependencies
      - name: Install Node.js dependencies
        run: npm ci

      # Run linters
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          commit_message: Fix styling

  test:
    name: Unit Test
    if: ${{ needs.run-linters.result == 'success' }}
    needs: run-linters # This ensures that this job only runs if the run-linters job was successful
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Install required deps for action
      - name: Install Dependencies
        run: npm install

      # Finally, run our tests
      - name: Run the tests
        run: npm test       

  snyk:
    name: Security Tests
    if: ${{ needs.test.result == 'success' }}
    needs: test # This ensures that this job only runs if the test job was successful
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: snyk/actions/setup@master
      - name: Snyk Code Test
        continue-on-error: true
        run: snyk code test --sarif > snyk_sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Upload results to Github Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk_sarif



